name: asset_file_generator
description: A command-line application used to generate asset file in flutter project.
version: 0.0.1
repository: https://github.com/himanshugarg08/asset_file_generator
homepage: https://github.com/himanshugarg08/asset_file_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  macos:
  windows:

dependencies:
  args: ^2.3.0

executables:
  afg: asset_file_generator

dev_dependencies:
  pedantic: ^1.10.0
